[package]
authors = ["Abhimanyu Sharma <abhimanyusharma003@gmail.com>", "Ismael Belisario <ismael.beli.com@gmail.com>"]
edition = "2024"
name = "qubit"
version = "0.2.0"

[dependencies]
iced = "0.14.0"
lazy_static = "1.5.0"
pest = "2.8.4"
pest_derive = "2.8.4"
web-sys = "0.3.83"
